/// <reference path="../bower_components/DefinitelyTyped/angularjs/angular.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/angularjs/angular-resource.d.ts" />
/// <reference path="../bower_components/DefinitelyTyped/angular-ui-bootstrap/angular-ui-bootstrap.d.ts" />
/// <reference path="ng-commons.ts" />
/// <reference path="services/ng-resources.ts" />
/// <reference path="services/ng-user.ts" />
/// <reference path="directives/navbar/navbar.ts"/>
/// <reference path="directives/input/input.ts"/>
/// <reference path="directives/loading/loading.ts"/>
